### ISSUE TITLE
NonEmpty Vectors

### ISSUE THREAD

**Issue by emilypi** [mstksg/nonempty-containers#3]
Hey @mstksg - loving the library! Would you mind a PR for non-empty vectors, or do you have a particular reason why this was not included? I'd be happy to take this on.

**Comment by mstksg** [comment]
Hi @emilypi ; the main reason I think was that I was trying to more or less directly copy the *containers* API, so I didn't really think about anything outside of it.  However I'd definitely appreciate a non-empty vectors addition :)  It works well with the `HasNonEmpty` typeclass.  If a mutable version was there we could even have a `Vector` instance for it, so you can use normal *Data.Vector.Generic* functions on it ...but I'm not sure if that last step would be worth the trouble.  Feel free to let me know if you have any issues making things fit with the rest of the library!

**Comment by emilypi** [comment]
Someone gave me a good argument to the contrary - `Vector` is very GHC specific and would require more consistent maintenance than `containers`, which is "bare haskell". That makes it a good candidate to split off so we're not constantly forcing people to bump their `nonempty-containers` version. That's convincing to me, so I'll probably do that instead.

**Comment by emilypi** [comment]
To update, here's `nonempty-vector` - https://hackage.haskell.org/package/nonempty-vector

If `nonempty-containers` depends on this, then I can update it freely and we can include it as a container (as it should be considered) with a `HasNonEmpty` instance!

**Comment by mstksg** [comment]
Solved in #4 and up on hackage as 0.3.2.0 :)
